version: "3"

services: 
    brickbot:
        build: .
        ports: 
            - 8080:8080
        volumes: 
            - ./:/app
        working_dir: /app
        command: ['python', 'main.py']