version: "3"

services:
  brickbot:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app:ro
      - /var/log/saaya.log:/var/log/saaya.log
    working_dir: /app
    command: [ 'python', 'main.py' ]